#!/bin/sh


xslfile=/home/bunke/ejdev/zbw.ejpdf/zbw/ejpdf/browser/cover.xsl
xmlfile=$1
pdffile=`echo $1 | sed 's/.xml/.pdf/'`
fofile=$1.fo
#fopconf=/home/bunke/XSL/fop/userconfig.xml
fopconf=/home/bunke/.fop/fop.xconf

xsltproc -o $fofile -xinclude $xslfile $xmlfile && \
        fop -c $fopconf $fofile $pdffile && \
#        xmltex $fofile
        rm $fofile && \
        exec evince $pdffile
        
